This is makeindex, version 2.15 [MiKTeX 2.9.6300] (kpathsea + Thai support).
Scanning style file ./PowerElectronicsReference.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file PowerElectronicsReference.acn....done (113 entries accepted, 0 rejected).
Sorting entries....done (784 comparisons).
Generating output file PowerElectronicsReference.acr....done (85 lines written, 0 warnings).
Output written in PowerElectronicsReference.acr.
Transcript written in PowerElectronicsReference.alg.
