This is makeindex, version 2.15 [MiKTeX 2.9.6300] (kpathsea + Thai support).
Scanning style file ./transistors.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file transistors.acn....done (1 entries accepted, 0 rejected).
Sorting entries...done (0 comparisons).
Generating output file transistors.acr....done (6 lines written, 0 warnings).
Output written in transistors.acr.
Transcript written in transistors.alg.
